[package]
authors = ["Finomnis <finomnis@gmail.com>"]
edition = "2021"
readme = "README.md"
name = "imxrt-blinky"
version = "0.1.0"

[workspace]

[dependencies.rtic]
path = "../../rtic"
version = "2.0.1"
features = ["thumbv7-backend"]

[dependencies.rtic-monotonics]
path = "../../rtic-monotonics"
version = "2.0.0"
features = ["imxrt_gpt1"]

[dependencies]
embedded-hal = "0.2.7"
teensy4-panic = { version = "0.2.3", default-features = false }

[dependencies.teensy4-bsp]
features = ["rt"]
version = "0.4.4"

[dev-dependencies]
nb = "1.1.0" # Async
imxrt-log = { version = "0.1.1", default-features = false, features = [
    "log",
    "lpuart",
] }
log = "0.4.20"
imxrt-uart-panic = "0.1.1"

# this lets you use `cargo fix`!
[[bin]]
name = "imxrt-blinky"
test = false
bench = false

[profile.dev]
opt-level = 1
codegen-units = 16
debug = true
lto = false

[profile.release]
opt-level = "s"   # optimize for size
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
