init
the hal takes a duration of Duration { ticks: 45 }
timeout
the hal takes a duration of Duration { ticks: 45 }
hal returned 5
the hal takes a duration of Duration { ticks: 45 }
hal returned 5
now is MonotonicInstant { ticks: 213 }, timeout at MonotonicInstant { ticks: 263 }
the hal takes a duration of Duration { ticks: 35 }
hal returned 5 at time MonotonicInstant { ticks: 249 }
now is MonotonicInstant { ticks: 313 }, timeout at MonotonicInstant { ticks: 363 }
the hal takes a duration of Duration { ticks: 45 }
hal returned 5 at time MonotonicInstant { ticks: 359 }
now is MonotonicInstant { ticks: 413 }, timeout at MonotonicInstant { ticks: 463 }
the hal takes a duration of Duration { ticks: 55 }
timeout
