[package]
name = "rtic_hifive1"
categories = ["embedded", "no-std"]
description = "Examples of RTIC apps for the HiFive1 board"
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
rtic = { path = "../../rtic" }
hifive1 = { git = "https://github.com/romancardenas/hifive1.git", features = ["board-redv"] }
panic-halt = "0.2.0"
e310x = { git = "https://github.com/greenlsi/e310x.git", branch = "master", features = ["rt"]}
riscv-rt = {git = "https://github.com/rust-embedded/riscv.git"}
riscv = {git = "https://github.com/rust-embedded/riscv.git"}
riscv-semihosting = { git = "https://github.com/rust-embedded/riscv.git", branch = "semihosting" }

[features]
riscv-clint-backend = ["rtic/riscv-clint-backend"]
test-critical-section = []
