language: rust

matrix:
  include:
      # MSRV
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.36.0

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: stable

before_install: set -e

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
