//! examples/t-async-prio-limit-cap.rs
//!
//! Checks that the priority level RTIC hands to async HAL interrupts stays a valid priority when
//! a software task runs at the highest priority of the device.

#![no_main]
#![no_std]
#![deny(warnings)]
#![deny(missing_docs)]

use panic_semihosting as _;

extern "C" {
    static RTIC_ASYNC_MAX_LOGICAL_PRIO: u8;
}

#[rtic::app(device = lm3s6965, dispatchers = [SSI0])]
mod app {
    use cortex_m_semihosting::{debug, hprintln};

    #[shared]
    struct Shared {}

    #[local]
    struct Local {}

    #[init]
    fn init(_: init::Context) -> (Shared, Local) {
        // SAFETY: the static is generated by `#[rtic::app]` and never written to.
        let limit = unsafe { crate::RTIC_ASYNC_MAX_LOGICAL_PRIO };

        // One above `foo` is past the highest priority, so the limit is capped to it.
        hprintln!("async prio limit: {}", limit);

        debug::exit(debug::EXIT_SUCCESS); // Exit QEMU simulator

        (Shared {}, Local {})
    }

    #[task(priority = 8)]
    async fn foo(_: foo::Context) {}

    #[task(binds = UART0, priority = 1)]
    fn bar(_: bar::Context) {}
}
