//! examples/t-async-prio-limit.rs
//!
//! Checks the priority level RTIC hands to async HAL interrupts, such as monotonics. It must be
//! above every software task so those interrupts can preempt a blocking software task, and it
//! stays below the hardware tasks when the priority ranges allow it.

#![no_main]
#![no_std]
#![deny(warnings)]
#![deny(missing_docs)]

use panic_semihosting as _;

extern "C" {
    static RTIC_ASYNC_MAX_LOGICAL_PRIO: u8;
}

#[rtic::app(device = lm3s6965, dispatchers = [SSI0, QEI0])]
mod app {
    use cortex_m_semihosting::{debug, hprintln};

    #[shared]
    struct Shared {}

    #[local]
    struct Local {}

    #[init]
    fn init(_: init::Context) -> (Shared, Local) {
        // SAFETY: the static is generated by `#[rtic::app]` and never written to.
        let limit = unsafe { crate::RTIC_ASYNC_MAX_LOGICAL_PRIO };

        // `bar` sits right below `baz`, so the limit has to be raised to one above the software
        // tasks instead of one below the hardware task.
        hprintln!("async prio limit: {}", limit);

        debug::exit(debug::EXIT_SUCCESS); // Exit QEMU simulator

        (Shared {}, Local {})
    }

    #[task(priority = 1)]
    async fn foo(_: foo::Context) {}

    #[task(priority = 2)]
    async fn bar(_: bar::Context) {}

    #[task(binds = UART0, priority = 3)]
    fn baz(_: baz::Context) {}
}
